### ISSUE TITLE
-p/--pretty for automatic pretty print?

### ISSUE THREAD

**Issue by thedodd** [lmammino/jwtinfo#4]
Thanks for the great work. How would you feel about adding the aforementioned options for automatic pretty printing?

**Comment by lmammino** [comment]
Hello @thedodd, Thanks for the suggestion. I was Actually thinking about this and also adding something like --color but I will need to see if there's any option with serde or other libraries to get this. For now we are suggesting in the readme to pipe the output to `jq`

**Comment by stjepangolemac** [comment]
Not sure about color but I've submitted a PR that exposes a `--pretty` or `-P` parameter that nicely pads the output JSON.
