### ISSUE TITLE
Bash alternative?

### ISSUE THREAD

**Issue by xatier** [lmammino/jwtinfo#5]
Not an issue actually, but seems like one can have the following bash one-liner.

```bash
jwtinfo () 
{ 
    echo "$1" | cut -d'.' -f 2 | base64 -di 2> /dev/null
}
```

https://ideone.com/wlST3C

**Comment by lmammino** [comment]
Nice one! It might be worth adding this to the README :)

We will probably be adding some more functionality in the future like more verbose output that shows the signature details or whether the token is expired or not yet valid (or how long before these dates). At that point I guess having a dedicated software will make more sense.

Just for curiosity, can `base64` be used in URLsafe mode?

**Comment by xatier** [comment]
Hi @lmammino,

Would you elaborate a bit more on `URLsafe mode` with some examples?

**Comment by lmammino** [comment]
Of course @xatier.

I am going to quote [this excellent post](https://brockallen.com/2014/10/17/base64url-encoding/):

> **base64 encoding uses characters that do not work well in URLs and sometimes HTTP headers (e.g. the +, / and = characters are either reserved or have special meaning in URLs)**. URL encoding is designed to address that problem, but it’s sometimes error prone (e.g. double encoding) or the tooling just doesn’t do the right thing (IIS decodes %2F into a / before it arrives into the application and thus confuses the ASP.NET routing framework). It is very useful to put these sorts of values in a URL, but it’s also frustrating that it’s problematic and that we have to work around these issues again and again.
> 
> While reading the JWT specs they faced the same problem and they addressed it by using **base64url encoding (which is almost the same, yet different than base64 encoding). Base64url encoding is basically base64 encoding except they use non-reserved URL characters (e.g. – is used instead of + and _ is used instead of /) and they omit the padding characters**. I’ve been using this for some time now and am quite happy with it as a replacement for base64 encoding.

Just to give you an example here are the different encodings for this [favicon](https://loige.co/favicon.ico)

<img width="1165" alt="Screenshot 2020-03-09 at 21 54 01" src="https://user-images.githubusercontent.com/205629/76260838-9aaa9e00-6250-11ea-8d37-17e96b263d84.png">

**Comment by xatier** [comment]
By default, no, but we can tweak the input with `tr` to revert the substitution. The below is an example how to do that in bash.

https://github.com/Moodstocks/moodstocks-api-clients/blob/master/bash/base64url.sh

**Comment by lmammino** [comment]
I'll update the README in the next release to mention this alternative

**Comment by lmammino** [comment]
I'll leave this one open as a reminder until the README is updated ;)
